#!/bin/bash

# Function to get CPU information
get_cpu_info() {
    lshw -class processor | awk '/product/{print $2, $3, $4}'
}

# Function to get CPU speed
get_cpu_speed() {
    lscpu | awk '/CPU MHz/{print $3}'
}

# Function to get maximum CPU speed
get_max_cpu_speed() {
    lscpu | awk '/CPU max MHz/{print $4}'
}

# Function to get RAM information
get_ram_info() {
    free -h | awk '/Mem/{print $2}'
}

# Function to get disk information
get_disk_info() {
    lsblk -o NAME,ROTA,SIZE | awk 'NR>1{print $1, $2, $3}'
}

# Function to get video information
get_video_info() {
    lshw -class display | awk '/product/{print $2, $3, $4}'
}

# Function to get gateway IP
get_gateway() {
    ip route | awk '/default/{print $3}'
}

# Function to get DNS server
get_dns_server() {
    grep nameserver /etc/resolv.conf | awk '{print $2}'
}

# Function to get interface name and IP address
get_interface_info() {
    read -r interface ip_address <<< $(ip route | awk '/default/{print $5}' && ip addr show dev $interface | awk '/inet /{print $2}')
    echo "$interface $ip_address"
}

# Function to get listening ports
get_listening_ports() {
    ss -tuln | awk '/^tcp|^udp/{print $5}' | cut -d ':' -f2 | sort -n | uniq | tr '\n' ', '
}

# Function to get UFW rules
get_ufw_rules() {
    sudo ufw status numbered
}

# Get system information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)
CPU=$(get_cpu_info)
CPU_SPEED=$(get_cpu_speed)
MAX_CPU_SPEED=$(get_max_cpu_speed)
RAM=$(get_ram_info)
DISKS=$(get_disk_info)
VIDEO=$(get_video_info)
FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY=$(get_gateway)
DNS_SERVER=$(get_dns_server)
IFS=' ' read -r INTERFACE_NAME IP_ADDRESS <<< $(get_interface_info)
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ', ')
DISK_SPACE=$(df -h | awk '/^\/dev/{print $6, $4}')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
MEMORY_ALLOCATION=$(free -h | awk '/Mem/{print $3 "/" $2 " (" $7 " free)"}')
LISTENING_PORTS=$(get_listening_ports)
UFW_RULES=$(get_ufw_rules)

# Print system report
cat <<EOF

System Report generated by $USER, $(date)

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED / $MAX_CPU_SPEED MHz
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER
InterfaceName: $INTERFACE_NAME
IP Address: $IP_ADDRESS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES
EOF
